### ISSUE TITLE
QUESTION: How many log levels are supported?

### ISSUE THREAD

**Issue by JWilson45** [JaniAnttonen/winston-loki#119]
When using the logger I am only able to get a response from 3 log level functions:

```javascript
logger.info()
logger.warn()
logger.error()
```

Are there any other log levels that im missing?

**Comment by JaniAnttonen** [comment]
To my knowledge, it's configurable in winston itself – there's a filter for what levels get sent to transports.

**Comment by JaniAnttonen** [comment]
**Found the answer at https://github.com/winstonjs/winston#logging-levels**

winston allows you to define a level property on each transport which specifies the maximum level of messages that a transport should log. For example, using the syslog levels you could log only error messages to the console and everything info and below to a file (which includes error messages):
```
const logger = winston.createLogger({
  levels: winston.config.syslog.levels,
  transports: [
    new winston.transports.Console({ level: 'error' }),
    new winston.transports.File({
      filename: 'combined.log',
      level: 'info'
    })
  ]
});
```
You may also dynamically change the log level of a transport:
```
const transports = {
  console: new winston.transports.Console({ level: 'warn' }),
  file: new winston.transports.File({ filename: 'combined.log', level: 'error' })
};

const logger = winston.createLogger({
  transports: [
    transports.console,
    transports.file
  ]
});

logger.info('Will not be logged in either transport!');
transports.console.level = 'info';
transports.file.level = 'info';
logger.info('Will be logged in both transports!');
```
