### ISSUE TITLE
Snappy optionalDependency upgrade breaks build

### ISSUE THREAD

**Issue by razbensimon** [JaniAnttonen/winston-loki#131]
Hello,
In version 6.0.4 at this [PR](https://github.com/JaniAnttonen/winston-loki/pull/92) `snappy` got an upgrade to v7(7.1.1) from v6 (6.3.5).
That upgrade breaks our build with the following error:
![image](https://user-images.githubusercontent.com/5955905/232707428-7cd230a0-5f00-43c4-a7b7-5599685826a8.png)

Using pnpm `overrides` to get it back to 6.3.5 seems to work.
But I'm not sure what are the consequences of that in your library.

Hope you can solve the issue better than I 🙏🏼

**Comment by JaniAnttonen** [comment]
Related issue #137 closed due to latest release. Closing this as well. Might want to create two different releases with/without optional snappy dependency in the future.
