### ISSUE TITLE
How to configure the log properly

### ISSUE THREAD

**Issue by averri** [JaniAnttonen/winston-loki#19]
I think the documentation of this project is very poor. It does not give any example about how to configure and use the logger properly.

This is what I have configured for the logger:

```javascript
const {createLogger, format, transports} = require('winston')
const LokiTransport = require("winston-loki")
const {combine, timestamp, json, prettyPrint} = format

const logger = createLogger({
  level: 'info',
  format: combine(
    timestamp(),
    json()
  ),
  transports: [
    new transports.Console({
      level: 'debug',
      format: combine(
        prettyPrint()
      )
    }),
    new LokiTransport({
      level: 'info',
      host: "http://localhost:3100",
    })
  ]
})

module.exports = logger
```

Importing the `logger` into another module and calling:

```javascript
logger.info('Starting API...', {job: 'strenux'})
```

... I can see the logs in the console, but nothing appears in the Loki server, which is up and running at `http://localhost:3100`.

**Comment by JaniAnttonen** [comment]
Thanks for pointing this out! I'm sorry for the status of the project, been busy with work and studies so I haven't had that much time to work on personal open-source. :) I'll look into this during this week.

**Comment by averri** [comment]
@JaniAnttonen, no worries, I just wanted to highlight the issue with the documentation, this is an interesting project. I'm not aware of any other similar project for Loki+Winston. I don't know if there is anything wrong with my setup. If you add one or two examples of how to use it will be great.
