### ISSUE TITLE
JSON mode & Batching is not working

### ISSUE THREAD

**Issue by JoHuang** [JaniAnttonen/winston-loki#20]
https://github.com/JaniAnttonen/winston-loki/blob/f2919790f5515afeaf6511a8d72881cee9242edd/src/batcher.js#L144-L155

I think line 153, should be `reqBody = JSON.stringify(this.batch)`, or the entire reqBody would be undefined.

**Comment by JaniAnttonen** [comment]
Yes, you're correct. What an interesting brain fart that is :D I'll fix this in my open PR.

**Comment by JoHuang** [comment]
Maybe you should check the test case , too. 
It shows pass and that line is covered multiple times.
