### ISSUE TITLE
Confusing options batching & gracefulShutdown

### ISSUE THREAD

**Issue by JoHuang** [JaniAnttonen/winston-loki#28]
https://github.com/JaniAnttonen/winston-loki/blob/024f508fcaa637ffd844f91e9745a6ed3496c9f6/index.js#L21-L30

You use `!` in front of batching & gracefulShutdown, which means it's inverted.
So should I put true or false?

the results are:
In / out
undefined -> true
false->true
true->false

**Comment by JaniAnttonen** [comment]
Man I must've been tired last night :D

**Comment by JaniAnttonen** [comment]
5.1.2 published with your fixes. :)
