### ISSUE TITLE
Any plans to cut a new release?

### ISSUE THREAD

**Issue by yaron-idan** [JaniAnttonen/winston-loki#39]
First of all - thanks for this transport. I'm trying to use it to ship logs from our Lambda functions to our Loki instance and it looks like it's exactly what I need.
The current version in NPM is very different than the one currently in master. Any plans to cut a new release soon? Even an rc we can use to field test this module?

**Comment by JaniAnttonen** [comment]
Thanks.

After I merged your PR and did a release, I forgot to put the `--tag next` to `npm publish` and wasn't fast enough to cancel the request, so actually now the `latest` version is the one with your fix. Already handled this in the readme.

I'll merge the development branch to master as well. The transport seems to work, so I guess the previous coverage of 96% is not strictly needed. Happy that its seeing some use. :)

**Comment by yaron-idan** [comment]
Great stuff, thanks!
