### ISSUE TITLE
basic authentication header fails due to extra colon

### ISSUE THREAD

**Issue by yaron-idan** [JaniAnttonen/winston-loki#40]
I've tried using the basic authentication feature and failed.
It seems to be due to [this line](https://github.com/JaniAnttonen/winston-loki/blob/development/src/batcher.js#L35)

When removing the colon following `basic` the log is sent successfully.
I'll open a PR now to fix the issue.

**Comment by JaniAnttonen** [comment]
Thanks for the find and fix! Helps a lot in moving towards 6.x.x as the stable release :)
