### ISSUE TITLE
Erroneous console.log in latest rc

### ISSUE THREAD

**Issue by apmorton** [JaniAnttonen/winston-loki#47]
There are a few debug logs left in the batcher
https://github.com/JaniAnttonen/winston-loki/blob/7492899f019a7470f65fcff9bc593a235a388bcb/src/batcher.js#L187-L194

**Comment by JaniAnttonen** [comment]
Sorry for sleeping on this, will remove asap

**Comment by JaniAnttonen** [comment]
I'll also add a linter check for preventing this in the future. Thanks a lot for pointing this out @apmorton!
