### ISSUE TITLE
If options.interval is not specified and sendBatchToLoki throws, interval becomes 0

### ISSUE THREAD

**Issue by apmorton** [JaniAnttonen/winston-loki#48]
`this.options.interval` may be undefined:
https://github.com/JaniAnttonen/winston-loki/blob/fda379c68f9db0c4ca219350af854e6e0a55016f/src/batcher.js#L40-L43

`this.interval` is overwritten if `await this.sendBatchToLoki()` throws:
https://github.com/JaniAnttonen/winston-loki/blob/fda379c68f9db0c4ca219350af854e6e0a55016f/src/batcher.js#L228-L230

`Number(undefined) becomes 0`
https://github.com/JaniAnttonen/winston-loki/blob/fda379c68f9db0c4ca219350af854e6e0a55016f/src/batcher.js#L226

**Comment by apmorton** [comment]
#50 does not resolve this issue - the problem is on line 226 in the code snippets I linked above, not line 40 where you have added a strict equality comparison to undefined (which is not needed).

**Comment by JaniAnttonen** [comment]
Fixed in `6.0.0-rc.6`: https://github.com/JaniAnttonen/winston-loki/commit/17696e93cd551ff50f10835d37129608ac7c3948
