### ISSUE TITLE
not showing debug log in loki

### ISSUE THREAD

**Issue by navneetgarggate6** [JaniAnttonen/winston-loki#59]
I am using following code. I am seeing info level and error level but not debug level or logs what is the issue ?
logger.debug('I am a debug log')
logger.info('I am a info log')
logger.error('I am a error log')

**Comment by JaniAnttonen** [comment]
Not really an issue with winston-loki AFAIK, but with your logger config. When creating the winston logger, you must pass the log level option `level: "debug"` to show debug level logs: 
```javascript
const logger = winston.createLogger({
  level: 'debug',
  ...
});
```

**Comment by navneetgarggate6** [comment]
I am using the same level in my config. this is my code
```  
const winston = require('winston')
const LokiTransport = require("winston-loki");
const logger = winston.createLogger()

logger.add(new winston.transports.Console({
  format: winston.format.json(),
  level: 'debug'
}))

logger.add(new LokiTransport({
  host: 'http://127.0.0.1:3100',
  json: true,
  labels: { job: 'winston-loki-example' }
}))

const wait = (duration) => new Promise(resolve => {
  setTimeout(resolve, duration)
})

const run = async () => {
  while (true) {
    logger.debug({ message: 'test', labels: { 'key': 'value' } })
    logger.debug('I am a debug log')
    logger.info('I am a info log')
    logger.error('I am a error log')
    await wait(1000)
  }
}

run()`

**Comment by JaniAnttonen** [comment]
You need to specify the logging level when creating the logger on line 3, the transport log level is separate.

**Comment by navneetgarggate6** [comment]
Thanks it is working now.
