### ISSUE TITLE
Logs with labels that have a number as value fail silently

### ISSUE THREAD

**Issue by niekcandaele** [JaniAnttonen/winston-loki#72]
Heya

When using code like the following, logs do not make it to Loki. Other logs were fine, but this particular line was never ending up in Loki.

```js
  logger.debug({
    message: 'bla bla bla',
    labels: { serverId: 2 }
  });
```

After some (read: a lot) of debugging I found that in the `then` [here](https://github.com/JaniAnttonen/winston-loki/blob/development/src/batcher.js#L197), the response is not used. However, adding a var there and debugging reveals an error message in the http response:

```
"loghttp.PushRequest.Streams: []*loghttp.Stream: loghttp.Stream.Entries: []loghttp.Entry: Labels: ReadString: expects \" or n, but found 2, error found in #10 byte of ...|erverId\":2,\"serverNa|..., bigger context ...|\"streams\":[{\"stream\":{\"level\":\"debug\",\"serverId\":2,\"serverName\":\"http://127.0.0.1:1337\",\"release\":\"1|...\n"
```
It seems to me that Loki returns a 200 on error, which causes the code not to fall into the `catch` block. I didn't verify this though :)

I fixed this on my side by making sure any labels I send are strings (and not numbers) but it'd be great if the library has a fallback for this. Or could propagate the error so the developer knows something is wrong.

Thanks for a great library :smiley:

**Comment by JaniAnttonen** [comment]
Thanks for a great submission! :)
