### ISSUE TITLE
Add basicAuth in README.md

### ISSUE THREAD

**Issue by clouedoc** [JaniAnttonen/winston-loki#86]
There is a `basicAuth` option as shown [in this example](https://github.com/JaniAnttonen/winston-loki/blob/development/examples/basicAuth.js).

However, this option does not appear in the README.md.

Related issue: #76 

I can open a PR if you'd like 😄

**Comment by JaniAnttonen** [comment]
Please, feel free! Couldn't really keep up to date without the help of the OS community :)
