### ISSUE TITLE
is this repo still working?

### ISSUE THREAD

**Issue by nort3x** [JaniAnttonen/winston-loki#90]
as grafana stated in their official website their api can undergo breaking changes,
and they didn't even listed this project even as an unofficial related library to their project

i hoped i could use this lib (which is currently most popular node lib related to loki) to use it's functionality but i struggled for +8 hours and couldn't make it work,

it's not **failing fast** i can't even tell if it's facing any issue or not, tried different configurations then used the provided example and tests and yet i can't get what i need

![Screenshot from 2021-12-24 22-22-45](https://user-images.githubusercontent.com/26030553/147369381-5da0d283-05f3-4ff3-8fdb-a4f3b5b4d9b0.png)

**Comment by olearycrew** [comment]
I'm currently in the same boat, having the same kind of results.  Hard to tell if the logs are even hitting the API.  I've downloaded and run directly from the latest code to try and figure it out.

**Comment by olearycrew** [comment]
Okay I think I sorted my problem - it was TLS related but there was no way to easily figure that out.

**Comment by nort3x** [comment]
the docker provided in example also is pulling `latest` loki and the example doesn't work with that , at least for a temporary solution we need to know which version it has been tested with

it's good piece of work and need more attention towards it <3

**Comment by jonim8or** [comment]
Could you maybe try with a fixed version of loki (instead of latest)? That would help clarify what is working and what not. 
I ran the examples with latest and 2.4.1, and they both work for me. 
![image](https://user-images.githubusercontent.com/12826624/149178003-fdd22aea-4142-46a9-a1fc-2985832c0257.png)

**Comment by crundberg** [comment]
The problem is that Winston returns the timestamp as a string and this transport expects a date. As a workaround I set the option replaceTimestamp to true.

https://github.com/JaniAnttonen/winston-loki/blob/8af9b480b921192d96bfdb6bc6263a828bf13996/index.js#L55-L84

**Comment by erfanandesta1373** [comment]
I use the latest for Loki, Grafana, and Promtail and it's working fine. Please consider that URL for Loki on Grafana must be http://loki:3100 and for winston-loki must be http://localhost:3100

**Comment by nort3x** [comment]
i see some contradictory comments here, let me test it with current main head at
 b825d3b7fd7369a0ccac1a46944d239e06765d1e

and i will report the results

**Comment by briosheje** [comment]
> The problem is that Winston returns the timestamp as a string and this transport expects a date. As a workaround I set the option replaceTimestamp to true.
> 
> https://github.com/JaniAnttonen/winston-loki/blob/8af9b480b921192d96bfdb6bc6263a828bf13996/index.js#L55-L84

That was my issue, thank you.
